const arr = [{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://kinofilmpro.ru/wp-content/uploads/2022/02/w1500_44943050.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://kinofilmpro.ru/wp-content/uploads/2022/02/w1500_44943050.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/60923ce1-f49e-4bf3-89b9-f3b8f537a0fc/3840x',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/60923ce1-f49e-4bf3-89b9-f3b8f537a0fc/3840x',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://w.forfun.com/fetch/4f/4f8e3d76671bcf1851bf41b7d15c3a4a.jpeg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://w.forfun.com/fetch/4f/4f8e3d76671bcf1851bf41b7d15c3a4a.jpeg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia',
    director: 'Александр Хант',
    duration: '2ч10м',
    year: '2017',
    description: 'djdhjkdhjdjk',
    image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/4716873/fc103b44-c7e1-4bb3-b9e4-b8be1bde549d/300x450',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Как Витька Чеснок вёз Лёху Штыря в дом инвалидов',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},
{
    country: 'Russia, USA',
    director: 'Виктор Гинзбург',
    duration: '2ч10м',
    year: '2011',
    description: 'djdhjkdhjdjk',
    image: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    trailerLink: 'https://www.kinopoisk.ru/film/104893/video/',
    thumbnail: 'https://www.indiewire.com/wp-content/uploads/2012/05/generation-p-original.jpg',
    nameRU: 'Generation П',
    nameEN: 'Generation P'
},

]

export default arr;


